exec:
	chmod +x *.py

pycode:
	pycodestyle *.py

test_all:
	python3 -m doctest ./tests/*

test_1:
	python3 -m doctest -v ./tests/1-my_list.txt

test_7:
	python3 -m doctest -v ./tests/7-base_geometry.txt
