test_0:
	python3 -m doctest -v ./tests/0-add_integer.txt

test_2:
	python3 -m doctest -v ./tests/2-matrix_divided.txt

test_3:
	python3 -m doctest -v ./tests/3-say_my_name.txt

test_4:
	python3 -m doctest -v ./tests/4-print_square.txt

test_5:
	python3 -m doctest -v ./tests/4-print_square.txt